version: "3.7"

volumes:
  db: {}

services:

  nginx:
    container_name: gitpab-nginx
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${HTTP_PORT}:80
    depends_on:
      - php
    environment:
      GITLAB_PRIVATE_TOKEN: ${GITLAB_PRIVATE_TOKEN}
      GITLAB_RESTRICTIONS_PROJECT_IDS: ${GITLAB_RESTRICTIONS_PROJECT_IDS}
      GITLAB_HOST: ${GITLAB_HOST}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    restart: always

  php:
    container_name: gitpab-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: app
    environment:
      GITLAB_PRIVATE_TOKEN: ${GITLAB_PRIVATE_TOKEN}
      GITLAB_RESTRICTIONS_PROJECT_IDS: ${GITLAB_RESTRICTIONS_PROJECT_IDS}
      GITLAB_HOST: ${GITLAB_HOST}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    restart: always

  db:
    container_name: gitpab-db
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gitpab
      POSTGRES_USER: gitpab
      POSTGRES_PASSWORD: gitpab
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    restart: always
